export const products = [
    {
        id: 1,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 2,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 3,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 4,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 5,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 6,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 7,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
    {
        id: 8,
        title: 'Samsung S21',
        description: 'Black in color',
        price: '250$',
        img: 'https://cdn.mos.cms.futurecdn.net/wAeDcpDmZrBecNdDt39QZa-1200-80.jpg',
        amount: 1,
    },
]